name: Update README with Quote

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight UTC
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install jq

      - name: Get random quote
        id: quote
        run: |
          curl -s https://api.quotable.io/random > quote.json
          echo "::set-output name=text::$(jq -r '.content' quote.json)"
          echo "::set-output name=author::$(jq -r '.author' quote.json)"

      - name: Update README
        run: |
          sed -i '/<!-- QUOTE_START -->/,/<!-- QUOTE_END -->/c\<!-- QUOTE_START -->\n> "${{ steps.quote.outputs.text }}"\n\n— **${{ steps.quote.outputs.author }}**\n<!-- QUOTE_END -->' README.md

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add README.md
          git commit -m "🤖 Update quote of the day" || echo "No changes to commit"
          git push
